# For parameter descriptions, please refer to the template parameter files for each node.

ekf_local:
  frequency: 20

  sensor_timeout: 0.1
  two_d_mode: false
  transform_time_offset: 0.0
  transform_timeout: 0.0
  print_diagnostics: true
  debug: false

  map_frame: global
  odom_frame: odom
  base_link_frame: hero
  world_frame: odom

  odom0: wheel/odometry
  odom0_config: [
      true, # x
      false, # y
      false, #z
      false, # roll
      false, # pitch
      false, # yaw
      false, # vx
      false, # vy
      false, # vz
      false, # vroll
      false, # vpitch
      false, # vyaw
      false, # ax
      false, # ay
      false, # az
    ]
  odom0_queue_size: 10
  odom0_nodelay: true
  odom0_differential: false
  odom0_relative: false

  imu0: imu/data
  imu0_config: [
      false, # x
      false, # y
      false, # z
      false, # roll
      false, # pitch
      true, # yaw
      false, # vx
      false, # vy
      false, # vz
      false, # vroll
      false, # vpitch
      false, # vyaw
      false, # ax
      false, # ay
      true, # az
    ]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

  use_control: false

  process_noise_covariance:
    [
      0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
      0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
      0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015
    ]

  initial_estimate_covariance:
    [
      1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9
    ]

ekf_global:
  frequency: 20
  sensor_timeout: 0.1
  two_d_mode: false
  transform_time_offset: 0.0
  transform_timeout: 0.0
  print_diagnostics: true
  debug: false

  odom_frame: odom
  base_link_frame: hero
  world_frame: global
  map_frame: global


  odom0: wheel/odometry
  odom0_config: [
      true,  # x
      false, # y
      false, # z
      false, # roll
      false, # pitch
      false, # yaw
      false, # vx
      false, # vy
      false, # vz
      false, # vroll
      false, # vpitch
      false, # vyaw
      false, # ax
      false, # ay
      false, # az
    ]
    
  odom0_queue_size: 10
  odom0_nodelay: false
  odom0_differential: false
  odom0_relative: false

  odom1: /odometry/gps
  odom1_config:
    [
      true,  # x
      true,  # y
      true,  # z
      false, # roll
      false, # pitch
      false, # yaw
      false, # vx
      false, # vy
      false, # vz
      false, # vroll
      false, # vpitch
      false, # vyaw
      false, # ax
      false, # ay
      false, # az
    ]
  odom1_queue_size: 10
  odom1_nodelay: false
  odom1_differential: false
  odom1_relative: false

  imu0: imu/data # with the "corrected covariance for yaw"
  imu0_config: [
      false, # x
      false, # y
      false, # z
      true, # roll
      true, # pitch
      true, # yaw
      false, # vx
      false, # vy
      false, # vz
      true, # vroll
      true, # vpitch
      true, # vyaw
      true, # ax
      true, # ay
      true, # az
    ]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

  use_control: false

  process_noise_covariance:
    [
    # x     y     z     roll  pitch yaw   vx     vy     vz    vroll vpitchvyaw  ax    ay    az    
      0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,    # x 
      0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,    # y
      0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,    # z
      0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,    # roll
      0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,    # pitch
      0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,    # yaw
      0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,    # vx
      0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,    # vy
      0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,    # vz
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,    # vroll
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,    # vpitch
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,    # vyaw
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,    # ax
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,    # ay
      0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015 # az
    ]

  initial_estimate_covariance:
    [
      1e-0, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    1e-0, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    1e-0, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    1e-0, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    1e-0, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    1e-0, 0,    0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    1e-0, 0,    0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    1e-0, 0,    0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    1e-0, 0,     0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-0,  0,     0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-0,  0,     0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-0,  0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-0, 0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-0, 0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-0
    ]

navsat_transform:
  frequency: 20
  delay: 0.1
  magnetic_declination_radians: -0.0429351 # For lat/long 55.944831, -3.186998
  yaw_offset: 3.14 #-1.570796327 # IMU reads 0 facing magnetic north, not east
  zero_altitude: false
  broadcast_utm_transform: false
  publish_filtered_gps: false
  
  use_odometry_yaw: true
  wait_for_datum: true # set in param or ### TODO: lets do this @malke with openDrive
  datum: [0.0, 0.0, 0.0]