image: map.png
resolution: 0.5  # The resolution of the map in meters per pixel
origin: [-200.0, -100.0, 0.0]  # The (x, y) position of the origin of the map, and orientation (yaw)
negate: 0  # Set to 1 if the map image has white as the free space
occupied_thresh: 0.65  # The threshold above which pixels are considered obstacles
free_thresh: 0.196  # The threshold below which pixels are considered free space
