name: 🐞 Bug
title: "[Bug]: "
description: A bug that requires attention.
labels: ["bug"]
body:
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: Describe the current, unexpected behavior.
      placeholder: The car doesn’t detect the traffic light on Map1.

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe the expected, correct behavior.
      placeholder: The car should detect the traffic light on Map1.

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
      placeholder: |
        * Start simulation on Map1.
        * After 600m, the car should stop at the traffic light.

  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: Criteria to consider this issue resolved.
      placeholder: |
        - The car detects traffic lights on Map1 correctly.
        - The issue no longer occurs in similar scenarios.

  - type: textarea
    id: testability
    attributes:
      label: Testability
      description: Describe how to test the fix.
      placeholder: Describe testing steps for verification.

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependent tasks or issues.
      placeholder: Link dependencies here (e.g., \#123).

  - type: markdown
    attributes:
      value: |
        **Add Group Label**:
        - perception: Related to sensor processing and scene understanding
        - planning: Related to path planning and decision making
        - acting: Related to vehicle control and actuation
        - system: Related to the general behavior of the system
        - research: Related to research and experimentation
        - infrastructure: Related to system infrastructure and setup

        **Add Labels on the Project Board**:
        **Priority:**
        - `Urgent`: Critical bug causing system crash, needs immediate fix.
        - `High`: Major feature request or significant bug affecting many users.
        - `Medium`: Minor feature request or bug with a workaround.
        - `Low`: Cosmetic changes or minor improvements.

        **Size:**
        - `Tiny`: Small typo fix or minor code refactor. Estimated time: 30 minutes.
        - `Small`: Simple bug fix or small feature addition. Estimated time: 1-2 hours.
        - `Medium`: Moderate feature addition or multiple bug fixes. Estimated time: 1-2 days.
        - `Large`: Major feature implementation or significant refactor. Estimated time: 1-2 weeks.
        - `X-Large`: Large-scale feature or complete module overhaul. Estimated time: 2-4 weeks. Especially `EPIC` issues should
          be tagged with this size.
