name: "General Issue"
title: "[General]: "
description: Template for general issues.
labels: ["general"]

body:
  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Describe the issue in detail.
      placeholder: |
        Enter description here:
        - What is the problem?
        - What is the expected outcome?

  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: Criteria for considering the task complete.
      placeholder: |
        - Implementation completed and tested
        - Documentation updated
        - Code review passed
        - All tests passing

  - type: textarea
    id: testability
    attributes:
      label: Testability
      description: How to verify the issue's resolution.
      placeholder: Enter test methods and validation criteria.

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List dependencies, if any.
      placeholder: Link dependencies here (e.g., the issue \#789).

  - type: markdown
    attributes:
      value: |
        **Add Standard Label**:
        - bug: Something isn't working
        - enhancement: New feature or request
        - help wanted: Extra attention is needed
        - discussion: Discussion is needed
        - documentation: Improvements or additions to documentation
        - question: Further information is requested
        - wontfix: This will not be worked on

        **Add Group Label**:
        - perception: Related to sensor processing and scene understanding
        - planning: Related to path planning and decision making
        - acting: Related to vehicle control and actuation
        - system: Related to the general behavior of the system
        - research: Related to research and experimentation
        - infrastructure: Related to system infrastructure and setup

        **Add Labels on the Project Board**:
        **Priority:**
        - `Urgent`: Critical bug causing system crash, needs immediate fix.
        - `High`: Major feature request or significant bug affecting many users.
        - `Medium`: Minor feature request or bug with a workaround.
        - `Low`: Cosmetic changes or minor improvements.

        **Size:**
        - `Tiny`: Small typo fix or minor code refactor. Estimated time: 30 minutes.
        - `Small`: Simple bug fix or small feature addition. Estimated time: 1-2 hours.
        - `Medium`: Moderate feature addition or multiple bug fixes. Estimated time: 1-2 days.
        - `Large`: Major feature implementation or significant refactor. Estimated time: 1-2 weeks.
        - `X-Large`: Large-scale feature or complete module overhaul. Estimated time: 2-4 weeks. Especially `EPIC` issues should
          be tagged with this size.
