name: "General Issue"
title: "[General]: "
description: Template for general issues.
labels: ["general"]

body:
  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Describe the issue in detail.
      placeholder: |
        Enter description here:
        - What is the problem?
        - What is the expected outcome?

  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: Criteria for considering the task complete.
      placeholder: |
        - Implementation completed and tested
        - Documentation updated
        - Code review passed
        - All tests passing

  - type: input
    id: effort_estimate
    attributes:
      label: Effort Estimate
      description: Approximate effort required (e.g., hours).
      placeholder: Enter effort estimate.

  - type: textarea
    id: testability
    attributes:
      label: Testability
      description: How to verify the issue's resolution.
      placeholder: Enter test methods and validation criteria.

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List dependencies, if any.
      placeholder: Link dependencies here (e.g., the issue \#789).

  - type: markdown
    attributes:
      value: |
        **Add Standard Label**:
        - bug: Something isn't working
        - enhancement: New feature or request
        - help wanted: Extra attention is needed
        - discussion: Discussion is needed
        - documentation: Improvements or additions to documentation
        - question: Further information is requested
        - wontfix: This will not be worked on

        **Add Priority Label**:
        - p1: Immediate attention
        - p2: High priority
        - p3: Standard priority
        - p4: Low priority

        **Add Group Label**:
        - perception: Related to sensor processing and scene understanding
        - planning: Related to path planning and decision making
        - acting: Related to vehicle control and actuation
        - system: Related to the general behavior of the system
        - research: Related to research and experimentation
        - infrastructure: Related to system infrastructure and setup
