name: "Issue"
description: "Report an issue with the project"
title: "<title>"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A clear and concise description of what the issue is."
      placeholder: "..."
    validations:
      required: true