jobs:
    markdownlint:
        name: Lint markdown files
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the linter with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: peterdavehello/markdownlint:0.32.2
                options: -v ${{ github.workspace }}:/md
                run: |
                    markdownlint .